/*사용자를 생성
    CREATE USER[USER NAME] IDENTIFIED BY [PASSWORD] 
*/
CREATE USER STU IDENTIFIED BY LOVE;
ALTER USER STU IDENTIFIED BY HOPE;
DROP USER STU;

GRANT CREATE  SESSION TO STU;

GRANT SELECT ON SCOTT.EMP_DDL TO STU;
GRANT INSERT ON SCOTT.EMP_DDL TO STU;

REVOKE SELECT, INSERT ON SCOTT.EMP_DDL FROM STU;
SELECT * FROM SCOTT.EMP_DDL;