SELECT EMPNO, ENAME, DEPT.DEPTNO,DNAME
FROM EMP, DEPT
/* FROM EMP JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO */
WHERE EMP.DEPTNO=DEPT.DEPTNO 
ORDER BY EMP.ENAME;

/* WHERE = 사원이라 지정한 데이터만 불러오게 하는 절
ORDER BY = 내림차순, 오름차순으로 정리해주는 절 */

/* DEPT 테이블과 EMP 테이블에서 사번, 사원명, 급여, 부서명을 0
검색하시오. 단, 급여가 2000 이상인 사원에 대하여 급여기준으로 내림차순 정렬할 것.  */

SELECT EMPNO, ENAME, SAL, DNAME
FROM DEPT JOIN EMP ON EMP.DEPTNO=DEPT.DEPTNO
WHERE SAL >=2000
ORDER BY SAL DESC;


/*DEPT 테이블과 EMP 테이블에서 사번, 사원명, 업무, 급여, 
부서명을 검색하시오. 단, 업무가 MANAGER이며 급여가 2500 이상인 
사원에 대해, 사번을 기준으로 오름차순 정렬할 것.*/
SELECT EMPNO, ENAME, JOB, SAL, DNAME
FROM DEPT NATURAL JOIN EMP
WHERE JOB='MANAGER' AND SAL>=2500
ORDER BY EMPNO;
/*내림차순 - DESC 오름차순 - ASC*/

/*EMP 테이블과 SALGRADE 테이블에서 사번, 사원명, 급여,
 등급을 검색하시오. 단, 등급은 급여가  LOSAL과 HISAL 범위에 포함되고 등급이 4이며
 급여를 기준으로 내림차순 정렬할 것.*/
 SELECT EMPNO, ENAME, SAL, GRADE
 FROM EMP A JOIN SALGRADE ON A.SAL BETWEEN LOSAL AND HISAL
 WHERE GRADE=4 
 ORDER BY SAL DESC;
 
 /* DEPT 테이블, EMP 테이블, SALGRADE 테이블에서 사번, 사원명, 
부서명, 급여, 등급을 검색하시오. 단, 등급은 급여가 LOSAL과 HISAL 범위에 포함되며 
등급을 기준으로 내림차순 정렬할 것.*/
SELECT EMPNO, ENAME,DNAME, SAL, GRADE 
FROM EMP JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO 
        JOIN SALGRADE ON SAL BETWEEN LOSAL AND HISAL
ORDER BY SAL DESC;

/*EMP 테이블에서 사원명과 해당 사원의 
관리자명을 검색하시오.*/
SELECT E.ENAME 사원명, M.ENAME 관리자명
FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO;

/* EMP 테이블에서 사원명과 해당 사원의 관리자명, 
해당 사원의 관리자의 관리자명을 검색하시오. */
SELECT W.ENAME, MANAGER.ENAME, U.ENAME 
FROM EMP W JOIN EMP MANAGER ON W.MGR=MANAGER.EMPNO
JOIN EMP U ON MANAGER.MGR=U.EMPNO ;
/*7번 결과에서 상위 관리자가 없는 모든 사원의 이름도 
사원명에 출력되도록 수정하시오.*/










--Q3 부서별 고용인의 정보(수업 내용)
-- 부서코드 부서명 사원번호 이름 직급 봉급 
-- 부서번호는 역순, 사원명은 정렬로 표현
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO(+)=D.DEPTNO
ORDER BY D.DEPTNO DESC,E.ENAME ASC;
--Q4 부서별
--부서코드 부서명 사번 사원명 관리자사번
--해당 사원의 급여 급여등급 등급최저급여 등급 최고급여
SELECT D.DEPTNO 부서번호 ,D.DNAME 부서명, E.EMPNO 사번,E.ENAME 사원명, E.MGR 관리자명
      ,E2.ENAME AS MGR_ENAME,E.SAL, S.GRADE, S.LOSAL 등급최저급여, S.HISAL 등급최고급여
FROM EMP E 
RIGHT OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO 
/*LEFT OUTER JOIN SALGRADE S ON E.SAL>=S.LASAL AND E.SAL<=S.HISAL*/
LEFT OUTER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
LEFT OUTER JOIN EMP E2 ON E.MGR=E2.EMPNO
ORDER BY D.DEPTNO,E.EMPNO;

--Q1 ALLEN 사원의 직급과 동일한 사원들의 
-- 직급 사번 상원명 봉급 부서코드 부서명(INLINE VIEW)
SELECT E.JOB, E.EMPNO,E.ENAME, E.SAL, D.DEPTNO, D.DNAME
FROM EMP E,DEPT D 
WHERE E.DEPTNO = D.DEPTNO
AND E.JOB = (SELECT E1.JOB FROM EMP E1 WHERE E1.ENAME = 'ALLEN');

--Q2 전체 평균 급여보다 많이 받는 사원의
--사번 사원명 입사일(YYYY-MM-DD) 부서명 부서위치 급여 급여등급
SELECT E.EMPNO, E.ENAME,TO_CHAR(E.HIREDATE,'YYYY-MM-DD') HIREDATE
        ,D.DNAME, D.LOC, E.SAL, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO=D.DEPTNO AND E.SAL BETWEEN S.LOSAL AND S.HISAL
AND E.SAL>(SELECT AVG(SAL) FROM EMP)
ORDER BY E.SAL DESC,E.ENAME;

--Q3 10번 부서의 인원 중 30번 부서에 없는 직급을 가진 직원의 
--사번 사원명 직급 부서코드 부서명 부서위치
SELECT E.EMPNO, E.ENAME, E.JOB, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
AND E.DEPTNO=10 AND NOT E.JOB /*IN*/ <>ALL
(SELECT DISTINCT E1.JOB FROM EMP E1 WHERE E1.DEPTNO=30);


--Q4 SALESMAN의 최대급여보다 많이 급여를 받는 사람들의 
--사번 사원명 급여 급여등급
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL>(SELECT MAX(SAL) FROM EMP WHERE JOB='SALESMAN');
/*위, 아래 같은 의미*/
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND E.SAL>(SELECT MAX(SAL) FROM EMP WHERE JOB='SALESMAN');
